# Examen Pandas – Dataset Premier League

In [2]:
import pandas as pd
premier = pd.read_csv('premier.csv')
premier.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 571 entries, 0 to 570
Data columns (total 59 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Name                    571 non-null    object
 1   Jersey Number           563 non-null    float64
 2   Club                    571 non-null    object
 3   Position                571 non-null    object
 4   Nationality             570 non-null    object
 5   Age                     570 non-null    float64
 6   Appearances             571 non-null    int64
 7   Wins                    571 non-null    int64
 8   Losses                  571 non-null    int64
 9   Goals                   571 non-null    int64
 10  Goals per match         309 non-null    float64
 11  Headed goals            502 non-null    float64
 12  Goals with right foot   502 non-null    float64
 13  Goals with left foot    502 non-null    float64
 14  Penalties scored        309 non-null    float64
 15  Freekicks scored        309 non-null    float64
 16  Shots                   309 non-null    float64
 17  Shots on target         309 non-null    float64
 18  Shooting accuracy %     309 non-null    object
 19  Hit woodwork            502 non-null    float64
 20  Big chances missed      309 non-null    float64
 21  Clean sheets            262 non-null    float64
 22  Goals conceded          262 non-null    float64
 23  Tackles                 502 non-null    float64
 24  Tackle success %        390 non-null    object
 25  Last man tackles        193 non-null    float64
 26  Blocked shots           502 non-null    float64
 27  Interceptions           502 non-null    float64
 28  Clearances              502 non-null    float64
 29  Headed Clearance        502 non-null    float64
 30  Clearances off line     193 non-null    float64
 31  Recoveries              390 non-null    float64
 32  Duels won               390 non-null    float64
 33  Duels lost              390 non-null    float64
 34  Successful 50/50s       390 non-null    float64
 35  Aerial battles won      390 non-null    float64
 36  Aerial battles lost     390 non-null    float64
 37  Own goals               262 non-null    float64
 38  Errors leading to goal  459 non-null    float64
 39  Assists                 571 non-null    int64
 40  Passes                  571 non-null    int64
 41  Passes per match        571 non-null    float64
 42  Big chances created     502 non-null    float64
 43  Crosses                 502 non-null    float64
 44  Cross accuracy %        390 non-null    object
 45  Through balls           390 non-null    float64
 46  Accurate long balls     459 non-null    float64
 47  Saves                   69 non-null     float64
 48  Penalties saved         69 non-null     float64
 49  Punches                 69 non-null     float64
 50  High Claims             69 non-null     float64
 51  Catches                 69 non-null     float64
 52  Sweeper clearances      69 non-null     float64
 53  Throw outs              69 non-null     float64
 54  Goal Kicks              69 non-null     float64
 55  Yellow cards            571 non-null    int64
 56  Red cards               571 non-null    int64
 57  Fouls                   571 non-null    int64
 58  Offsides                502 non-null    float64
dtypes: float64(43), int64(9), object(7)
memory usage: 263.3+ KB

In [3]:
premier.describe()

,Jersey Number,Age,Appearances,Wins,Losses,Goals,Goals per match,Headed goals,Goals with right foot,Goals with left foot,...,Punches,High Claims,Catches,Sweeper clearances,Throw outs,Goal Kicks,Yellow cards,Red cards,Fouls,Offsides
count,563.000000,570.000000,571.000000,571.000000,571.000000,571.000000,309.000000,502.000000,502.000000,502.000000,...,69.000000,69.000000,69.000000,69.000000,69.000000,69.000000,571.000000,571.000000,571.000000,502.000000
mean,19.534636,25.789474,68.823117,28.957968,23.896673,7.327496,2.648414,1.414343,4.468127,2.388446,...,24.652174,45.869565,20.782609,25.565217,210.000000,414.144928,7.917688,0.301226,53.033275,11.063745
std,14.273515,4.377354,81.797516,38.969376,28.488376,16.810490,8.002117,3.433374,11.048341,6.295652,...,46.282644,82.332167,43.058397,47.333758,334.822473,641.246265,11.556811,0.698607,75.605560,26.570058
min,1.000000,17.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,8.000000,22.000000,3.000000,1.000000,1.000000,0.000000,0.050000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
50%,18.000000,26.000000,36.000000,12.000000,14.000000,1.000000,0.140000,0.000000,1.000000,0.000000,...,2.000000,6.000000,3.000000,4.000000,39.000000,53.000000,3.000000,0.000000,22.000000,2.000000
75%,27.000000,29.000000,108.000000,41.000000,36.000000,6.000000,0.390000,1.000000,3.000000,2.000000,...,31.000000,45.000000,17.000000,28.000000,300.000000,527.000000,11.000000,0.000000,74.000000,8.750000
max,82.000000,38.000000,539.000000,272.000000,158.000000,180.000000,57.000000,31.000000,127.000000,63.000000,...,269.000000,391.000000,249.000000,257.000000,1516.000000,2806.000000,81.000000,5.000000,438.000000,203.000000

### 1️⃣ Media de edad de los jugadores del Arsenal


Calcula la **edad media** de los jugadores cuyo club sea **Arsenal**.

In [42]:
edad_arsenal = premier.loc[premier['Club'] == 'Arsenal', 'Age'].mean()
print("La edad media de los jugadores del Arsenal es: ",edad_arsenal)

La edad media de los jugadores del Arsenal es:  25.1

### 2️⃣ Jugador del Liverpool con más y menos goles


Muestra el **jugador del Liverpool** que haya marcado **más goles** y el que haya marcado **menos goles**.

In [40]:
# Escribe tu código aquí
datosLiverpool = premier[premier['Club']== 'Liverpool']
mayorGoleador = datosLiverpool.sort_values('Goals',ascending=False).head(1)['Name']
menorGoleador = datosLiverpool.sort_values('Goals',ascending=True).head(1)['Name']
print("El mayor goleador del Liverpool es: \n",mayorGoleador)
print("\nEl menor goleador del Liverpool es: \n",menorGoleador)

El mayor goleador del Liverpool es:
 313    Sadio Mané
Name: Name, dtype: object

El menor goleador del Liverpool es:
 286    Loris Karius
Name: Name, dtype: object

### 3️⃣ Equipos con más tarjetas rojas


Calcula el **número total de tarjetas rojas por club** (`Red cards`).  
Ordena los resultados de mayor a menor y muestra los **5 equipos con más expulsiones**.

In [11]:
# Escribe tu cimport pandas as pd
equipos_tarjetas = premier.groupby('Club')['Red cards'].sum()
tarjetas_ordenadas = equipos_tarjetas.sort_values(ascending=False).head(5)

print("Los 5 equipos con mas expulsiones son:\n",tarjetas_ordenadas)

Los 5 equipos con mas expulsiones son:
 Club
Leicester-City      17
Newcastle-United    16
Crystal-Palace      14
Arsenal             13
Liverpool           12
Name: Red cards, dtype: int64

### 4️⃣ Nacionalidades


- ¿Cuántas **nacionalidades diferentes** hay en la liga?  
- ¿Cuál es la **nacionalidad más frecuente**?

In [32]:
# Escribe tu código aquí
nacionalidades_diferentes = premier['Nationality'].nunique()
print ("En la premier tenemos ",nacionalidades_diferentes," nacionalidades diferentes")

En la premier tenemos  57  nacionalidades diferentes

In [25]:
nacionalidad_frecuente = premier['Nationality'].value_counts()
print("La nacionalidad mas frecuente es:\n",nacionalidad_frecuente.head(1))

La nacionalidad mas frecuente es:
 Nationality
England    221
Name: count, dtype: int64

### 5️⃣ Top 10 jugadores con más asistencias


Muestra los **10 jugadores con mayor asistencias** (`Assits`).  
Incluye las columnas: `Name`, `Club`, y `Assits`.

In [35]:
# Top 10 jugadores con más asistencias
copia_premier = premier.copy()
top10_asistencias = copia_premier[['Name', 'Club', 'Assists']].sort_values('Assists', ascending=False).head(10)
print(top10_asistencias)

                 Name               Club  Assists
302      James Milner          Liverpool       84
335   Kevin De Bruyne    Manchester-City       67
13         Mesut Özil            Arsenal       54
365         Juan Mata  Manchester-United       52
198      Theo Walcott            Everton       51
344     Sergio Agüero    Manchester-City       46
304  Jordan Henderson          Liverpool       46
342   Raheem Sterling    Manchester-City       45
185  Gylfi Sigurdsson            Everton       45
345      Riyad Mahrez    Manchester-City       40

### 6️⃣ Clasificación de jugadores por goles


Crea una nueva columna llamada `Rango_goles` que clasifique a los jugadores según sus goles (`Goals`):  
- **Sin gol** → 0 goles  
- **Pocos goles** → entre 1 y 4 goles  
- **Goleador** → 5 o más goles  

Después, muestra cuántos jugadores hay en cada categoría.

In [31]:
# Escribe tu código aquí
premier['Rango Goles'] = pd.cut(
    premier['Goals'],
    bins = [-1,0,4,premier['Goals'].max()],
    labels = ['Sin Gol', 'Pocos Goles', 'Goleador'],
)
premier['Rango Goles'].value_counts()

Rango Goles
Sin Gol        254
Goleador       175
Pocos Goles    142
Name: count, dtype: int64

### 7️⃣ Tabla pivote con media de goles y asistencias por posición


Crea una **tabla pivote** que muestre la **media de goles y asistencias** (`Goals`, `Assists`)  
por **posición de juego** (`Position`).

In [ ]:
# Escribe tu código aquí
pd.pivot_table(premier, 
                values=['Goals','Assists'],
                index="Position", 
                aggfunc=["mean"]
               ).round(2)

              mean
           Assists  Goals
Position
Defender      3.33   2.66
Forward       8.52  21.48
Goalkeeper    0.16   0.00
Midfielder    7.19   6.59


---
## **Criterios de evaluación (10 puntos)**
| Criterio | Puntos |
|-----------|--------|
| Carga y exploración del dataset | 1 |
| Media de edad (filtros) | 1 |
| Jugador con más y menos goles | 1.5 |
| Agrupaciones y ordenamientos | 1.5 |
| Conteo y frecuencia de valores | 1 |
| Creación de nuevas columnas | 1 |
| Segmentación (`cut`) | 1 |
| Tabla pivote final | 2 |

# Examen Numpy

 ## Ejercicio: Análisis de Consumo Energético

Un contador inteligente registra el consumo de energía (en kWh) cada hora durante un día.

Analiza:

1. ¿A qué hora hubo el consumo máximo y cuál fue su valor?
2. ¿A qué hora se registró el consumo mínimo?
3. Calcula el consumo total del día.
4. Calcula el consumo promedio por hora.
5. ¿En cuántas horas el consumo superó los 2 kWh?
6. Muestra las horas en las que el consumo estuvo entre 1 y 2 kWh.

In [1]:
consumo = np.array([
  0.6, 0.5, 0.4, 0.3, 0.5, 0.7, 1.2, 1.8, 2.4, 3.0, 
  3.2, 3.5, 3.8, 3.6, 3.0, 2.8, 2.5, 2.0, 1.5, 1.2, 
  1.0, 0.8, 0.7, 0.6
])

NameError: name 'np' is not defined